# Generated by Django 3.1.7 on 2021-03-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0012_auto_20210322_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magnetic_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('datetime', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('X', models.FloatField()),
                ('Y', models.FloatField()),
                ('Z', models.FloatField()),
                ('F', models.FloatField()),
                ('area_code', models.CharField(max_length=10)),
                ('observatory', models.CharField(max_length=10)),
                ('graph', models.FileField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
