# Generated by Django 3.1.7 on 2021-03-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0013_magnetic_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magnetic_data',
            name='observatory',
            field=models.CharField(max_length=100),
        ),
    ]
